### ISSUE TITLE
Prometheus Webhook error with AlertManager 0.8.0 version

### ISSUE THREAD

**Issue by chandrasekarkr** [alerta/prometheus-config#6]
Below error appears while trying to integrate AlertManager 0.8.0 with Alerta Prometheus Webhook config. The error does not appear with AlertManager 0.7.1 version.

```
127.0.0.1 - - [22/Sep/2017 05:00:35] "POST /webhooks/prometheus HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python2.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/usr/lib/python2.7/site-packages/alerta_server-4.10.0-py2.7.egg/alerta/app/auth.py", line 157, in wrapped
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/alerta_server-4.10.0-py2.7.egg/alerta/app/webhooks/views.py", line 382, in prometheus
    incomingAlert = parse_prometheus(alert, external_url)
  File "/usr/lib/python2.7/site-packages/alerta_server-4.10.0-py2.7.egg/alerta/app/webhooks/views.py", line 339, in parse_prometheus
    text = description or summary or '%s: %s on %s' % (labels['job'], labels['alertname'], labels['instance'])
KeyError: 'job'
```

**Comment by satterly** [comment]
What does your prometheus.yml config file look like? If you define a `job_name` then alertmanager should fill in the "job" label. 

```
type ScrapeConfig struct {
	// The job name to which the job label is set by default.
	JobName string `yaml:"job_name"`
```
https://github.com/prometheus/prometheus/blob/master/config/config.go#L548

Are you able to capture the alertmanager webhook output? Point the webhook at https://requestb.in/

**Comment by chandrasekarkr** [comment]
Prometheus configuration was taken from default config [file](https://github.com/alerta/prometheus-config/blob/master/config/prometheus.yml).

Alert Manager console was also throwing HTTP500 error related to webhook

**Comment by satterly** [comment]
Any chance you could provide me with the request body of the failing HTTP POST? That would help a lot.

**Comment by chandrasekarkr** [comment]
I'm getting X.509 security error message while substituting https://requestb.in URL
`DEBU[1429] Notify attempt 12 for "webhook" failed: Post https://requestb.in/: x509: certificate signed by unknown authority  source="notify.go:585`

**Comment by chandrasekarkr** [comment]
Actual error message in Prometheus Alert Manager 0.8.0 appears as below:
`DEBU[1658] Notify attempt 6 for "webhook" failed: unexpected status code 500 from http://localhost:8080/webhooks/prometheus  source="notify.go:585"`

**Comment by satterly** [comment]
alertmanager is refusing to post to https://requestb.in because it looks like the SSL cert isn't configured properly. try http://requestb.in (ie http not https) instead.

**Comment by satterly** [comment]
SSL Labs says it's ok so i'm confused. https://www.ssllabs.com/ssltest/analyze.html?d=requestb.in

**Comment by n0guest** [comment]
We have AlertManager 0.8.0 which posts to Alerta 4.10.3 webhooks over HTTPS. And it works fine, at least now. For the SSL issue something like this could help with troubleshooting:

```
echo q | openssl s_client -CApath /etc/ssl -connect requestb.in:443 -servername requestb.in
```

This will show does your system trusts to remote certificate or not (but it should, they have a valid one).

**Comment by satterly** [comment]
Please provide the POST body of the prometheus alertmanager webhook otherwise we can't go much further in attempting to diagnose this issue. Thanks.

**Comment by satterly** [comment]
Closing for now. Reopen if/when you have more information.

**Comment by vermasuraj10678** [comment]
Hi Satterly,

I am intermittenlty getting below error in my alertmanager logs.

level=error ts=2019-06-11T15:25:14.197Z caller=dispatch.go:264 component=dispatcher msg="Notify for alerts failed" num_alerts=5 err="unexpected status code 500 from http://alerta:80/api/webhooks/prometheus?api-key=********************************"

Can you please guide me when it happens as i am getting no clue from this error, where it is holding alertmanager to send notification to alerta.

**Comment by satterly** [comment]
You need to provide the actual error message associated with the 500 status code.

**Comment by vermasuraj10678** [comment]
I am getting this error in uwsgi service logs - 

Jun 11 18:30:36 alerta alertad[52]: ERROR:flask.app:Severity is not one of fatal, critical, warning, ok, indeterminate, unknown
                                    Traceback (most recent call last):
                                      File "/opt/alerta/lib/python3.5/site-packages/alerta/utils/api.py", line 61, in process_alert
                                        alert = alert.update(is_correlated)
                                      File "/opt/alerta/lib/python3.5/site-packages/alerta/models/alert.py", line 326, in update
                                        self.trend_indication = alarm_model.trend(self.previous_severity, self.severity)
                                      File "/opt/alerta/lib/python3.5/site-packages/alerta/models/alarms/alerta.py", line 106, in trend
                                        assert current in StateMachine.Severity, 'Severity is not one of %s' % ', '.join(valid_severities)
                                    AssertionError: Severity is not one of fatal, critical, warning, ok, indeterminate, unknown
                                    
                                    During handling of the above exception, another exception occurred:
                                    
                                    Traceback (most recent call last):
                                      File "/opt/alerta/lib/python3.5/site-packages/alerta/webhooks/custom.py", line 46, in custom
                                        alert = process_alert(alert)
                                      File "/opt/alerta/lib/python3.5/site-packages/alerta/utils/api.py", line 65, in process_alert
                                        raise ApiError(str(e))
                                    alerta.exceptions.ApiError: Severity is not one of fatal, critical, warning, ok, indeterminate, unknown
                                    
                                    During handling of the above exception, another exception occurred:
                                    
                                    Traceback (most recent call last):
                                      File "/opt/alerta/lib/python3.5/site-packages/flask/app.py", line 1813, in full_dispatch_request
                                        rv = self.dispatch_request()
                                      File "/opt/alerta/lib/python3.5/site-packages/flask/app.py", line 1799, in dispatch_request
                                        return self.view_functions[rule.endpoint](**req.view_args)
                                      File "/opt/alerta/lib/python3.5/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
                                        resp = make_response(f(*args, **kwargs))
                                      File "/opt/alerta/lib/python3.5/site-packages/alerta/auth/decorators.py", line 50, in wrapped
                                        return f(*args, **kwargs)
                                      File "/opt/alerta/lib/python3.5/site-packages/alerta/webhooks/custom.py", line 60, in custom
                                        raise ApiError(str(e), 500)
                                    alerta.exceptions.ApiError: Severity is not one of fatal, critical, warning, ok, indeterminate, unknown
Jun 11 18:30:36 alerta alertad[52]:

**Comment by vermasuraj10678** [comment]
This is happening when i am recovering the resource. Alerts are not resolving on resource recovery and getting this error in uwsgi logs and below logs when checking alertmanager logs:
level=error ts=2019-06-11T18:29:54.177Z caller=notify.go:339 component=dispatcher msg="Error on notify" err="unexpected status code 500 from http://alerta:80/api/webhooks/prom
etheus?api-key=UdC1S9BOEeGQtHotvcGhEa2jFARJ_tkECNpIJG1b"
level=error ts=2019-06-11T18:29:54.177Z caller=dispatch.go:264 component=dispatcher msg="Notify for alerts failed" num_alerts=1 err="unexpected status code 500 from http://ale
rta:80/api/webhooks/prometheus?api-key=UdC1S9BOEeGQtHotvcGhEa2jFARJ_tkECNpIJG1b"
